# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.1
      #- image: circleci/postgres:9.4

    working_directory: /go/src/nikogura/gomason
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go get github.com/kardianos/govendor
      - run: govendor sync
      - run:  gpg-agent --daemon
#      - run:
#          name: Run Tests
#          command: go test -v ./...
      - go get github.com/mattn/goveralls
      - go test -v -cover -race -coverprofile=/home/circleci/coverage.out ./...
      - /home/circleci/.go_workspace/bin/goveralls -coverprofile=/home/circleci/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
