# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13.4

    working_directory: /go/src/github.com/nikogura/gomason
    environment:
      GO111MODULE: "on"
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: cp pkg/gomason/testfixtures/.gomason ~/.gomason
      - run: go get github.com/tools/godep
      - run: echo "[user]\n  email = gomason-tester@foo.com\n  username = gomason-tester\n[signing]\n  program = gpg" ~/.gomason
      - run: go get -v -t -d ./...
      - run: gpg-agent --daemon
      - run: go test -v ./...
      - run: go get github.com/mattn/goveralls
      - run: go test -v -cover -race -coverprofile=/tmp/coverage.out ./pkg/gomason
      - run: goveralls -coverprofile=/tmp/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
